# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be793a60bac85afa2c24cf6099753e6c8b49d625fcb9bc2fcce5e94bf361aee37f8365d3861e736462760fda16a36eeb6f2cfb9444e0a0e4e0b838073f288020

test:
  secret_key_base: 56441922dab20c6638bc0498200fde5b4ccd79c145b8046ff658b6b027c5e5fa6dc544c1978f7b5f0c65f5d61744f822d97bf4bed1a9152bf1b0b7546f2d3ba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
